### ISSUE TITLE
/tmp content does not clear after combinePDF()

### ISSUE THREAD

**Issue by DhyeyMoliya** [Rapidfacture/pdf-toolz#2]
I have found that when we use combinePDF(),
1. Library copies every PDF file to /tmp directory in Linux. 
2. After combining PDF, the resulting PDF is also stored in /tmp folder.

But, after that it is not cleared from /tmp folder and it stacks up in the Hard drive memory.

**Comment by FelixFurtmayr** [comment]
Hi DhyeyMoliya, thanks for the info.

I have not written the code, but I can ask my friend if we cannot solve the issue. So far I have one suggestion - can you try the following:

https://github.com/Rapidfacture/pdf-toolz/blob/master/SplitCombine.js

![grafik](https://user-images.githubusercontent.com/16761317/79017782-79501100-7b72-11ea-91e6-b58c7123f6be.png)

Set unsafeCleanup to false in your node_modules/pdf-toolz folder in the file SplitCombine.js. Does it work then?

**Comment by ulikoehler** [comment]
Thanks for reporting. I wrote the code. The cleanup part of the code is in this dependency:
https://www.npmjs.com/package/tmp
which is required by our wrapper:
https://github.com/Rapidfacture/with-tmp-dir-promise

We use tmp v0.0.33 but it has been updated to v0.1.0. Could you check if your issue persist with the new version of tmp?

**Comment by DhyeyMoliya** [comment]
Ok guys, @FelixFurtmayr  @ulikoehler  I will fork and check by updating dependency version if it solves the issue and give you further information.

**Comment by DhyeyMoliya** [comment]
Hello @FelixFurtmayr @ulikoehler , I checked and ran some tests :
1. I updated version of the dependency `tmp` to `0.1.0` via installing it with `npm i tmp`.
2. I also tried to change `unsafeCleanup` to `false` as well.

You can check my test case code at [https://github.com/DhyeyMoliya/pdf-toolz/blob/master/test/TMPClear.js](https://github.com/DhyeyMoliya/pdf-toolz/blob/master/test/TMPClear.js) in my fork [https://github.com/DhyeyMoliya/pdf-toolz](https://github.com/DhyeyMoliya/pdf-toolz)

Result : 
```In both the cases, the files are kept in /tmp folder until the process is exited.```

This is the result when test process is running.
![running](https://user-images.githubusercontent.com/6321840/79037881-90364800-7bf2-11ea-827e-f8d6bb706f81.png)

This is the result when test process is exited.
![completed](https://user-images.githubusercontent.com/6321840/79037894-ad6b1680-7bf2-11ea-8a7d-b23865c72656.png)


Now, the problem is, I am calling this library from a server process, which cannot be terminated each time the PDF operations are performed.

**Comment by FelixFurtmayr** [comment]
What about adding some console logs to see where the process is interrupted.
pdf-tools uses the npm module with-tmp-dir-promise https://github.com/Rapidfacture/with-tmp-dir-promise/blob/master/index.js

with-tmp-dir-promise uses the module tmp.

My suggestion - Step 1: Write a log into with-tmp-dir-promise:

![grafik](https://user-images.githubusercontent.com/16761317/79097579-600cb780-7d60-11ea-806f-657d160a3753.png)

Find out if options (path to delete) is passed correct. If not, we have to search somewhere before

Step 2: Everything seems to work so far - add also logs for the module "tmp". In tmp there has to be some methode to delete the stuff (maybe remove files with nodeJs, maybe execute something else). Eventually this does not work - can be a permission error etc.
If the problem should be here, I would try to isolate the "delete" code, and run it manual with the same options. Then you might get a proper error message.

**Comment by DhyeyMoliya** [comment]
@FelixFurtmayr I followed your instructions, I found that there is a minor problem in library [with-tmp-dir-promise](https://github.com/Rapidfacture/with-tmp-dir-promise).

I tried to change the code and I was successful in solving the problem.

I will share the code changes ASAP in the form of a Pull Request in [with-tmp-dir-promise](https://github.com/Rapidfacture/with-tmp-dir-promise) repo.

Thanks.

**Comment by DhyeyMoliya** [comment]
Hey @FelixFurtmayr, I saw that you have updated version to `1.1.2` and published npm package in [with-tmp-dir-promise](https://github.com/Rapidfacture/with-tmp-dir-promise). 

Can you please also update the `with-tmp-dir-promise` dependency version to `1.1.2` in `pdf-toolz` and publish this package to `npm`, so we can go ahead and update our own project dependency of pdf-toolz.

Thanks.

**Comment by FelixFurtmayr** [comment]
Was already on it, but somebody needed my attention.  It should be online now on npm. Thank you very much for your contribution!

**Comment by FelixFurtmayr** [comment]
I'm close this issue. Open it any time if there are further problems.
