### ISSUE TITLE
It is can used in windows?

### ISSUE THREAD

**Issue by jetBn** [Rapidfacture/pdf-toolz#3]

**Comment by FelixFurtmayr** [comment]
eventually when you have the correct dependencies: gm, ghostscript, pdftk. but it is untested there.
debugging: you can look into the code and try, if the commands work in your console directy.

**Comment by FelixFurtmayr** [comment]
we don't intend to get windows on our servers, so we don't work on a windows version. one alternative way for you to solve the issue might be, to put your app in a docker container, where linux is running.

I'm closing the issue as the question should be answered.

If you can install the dependencies and it works on your system you might tell us and we add it in the docs. Also you can make a pull request when you have suggestions for the code basis.

**Comment by jetBn** [comment]
ok
