### ISSUE TITLE
Advice on installing dependencies

### ISSUE THREAD

**Issue by mhkeller** [Rapidfacture/pdf-toolz#4]
It took me a little investigating to figure out how to get this working. Here are some steps that you find useful to add to the readme or just leave this issue up in case it helps other people.

1. You need graphics magick installed. I did this with `brew install graphicsmagick`
2. Unfortunately, graphics magick exposes itself on the command line as `gm`. My basic macOS git install had alias `gm` to `git merge` so I had to add `unalias gm` in my path. You can also do that line in your terminal but it will likely only last for that session. Some forum posts say you can remove the alias line in your global git config but it wasn't in mine.
3. I then encountered a `Postscript delegate failed` error so I needed to install the ghostscript library with `brew install gs`. 

That fixed it all.

Thanks for making this library! It's very useful.

**Comment by FelixFurtmayr** [comment]
Seems like you ran in some problems for the underlying packages. On Linux it is the same with graphicsmagick - also called gm. 

I don't see the permanent solution for you in step 2) but for me "gm" for graphicsmagick is just fine. I merge over the text editor or write it out.

I will ad at least some info about the dependencies in the readme. If you have a further suggestions to it, just create a merge request.

**Comment by FelixFurtmayr** [comment]
Alright, added this:

![grafik](https://user-images.githubusercontent.com/16761317/85505348-6932c400-b5ee-11ea-84e4-8cf3fb2859c2.png)

It is not for mac users, but they may easier find a way to deal with it.
Closing this issue. If you want to add something to the readme, create a pull request; or reopen the issue if further discussion is needed.

**Comment by mhkeller** [comment]
Thanks looks great
